#Application Configuration
server:
  port: 8092

spring:
  data:
      mongodb:
        uri: mongodb://localhost:27017/Cibertec
    
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"